### ISSUE TITLE
Upgrade to Webpack 4

### ISSUE THREAD

**Issue by pjconnors** [wearegenuine/gnorm#18]
Helpful upgrade information (the "how's" and "why's") can be found here: 
[Dev.to: Upgrade to Webpack 4 🎉](https://dev.to/flexdinesh/upgrade-to-webpack-4---5bc5)
[A tale of Webpack 4 and how to finally configure it in the right way](https://hackernoon.com/a-tale-of-webpack-4-and-how-to-finally-configure-it-in-the-right-way-4e94c8e7e5c1)

**Comment by ryanobrooks** [comment]
https://github.com/wearegenuine/gnorm/pull/19
